par(mfrow=c(1,1))

pharmodel <- lm(lpop~pharmacy, data = lpdata)
plot(lpdata$pharmacy, lpdata$lpop, xlab="pharmacy", ylab ="lpop")
abline(pharmodel)
summary(pharmodel)
summ(pharmodel)
par(mfrow=c(2,2))
plot(pharmodel,1)
plot(pharmodel,2)
plot(pharmodel,3)
plot(pharmodel,4)

lpdatapha <- lpdata[-c(23,9),]
pharmodel2 <- lm(lpop~pharmacy, data = lpdatapha)
plot(lpdatapha$pharmacy, lpdatapha$lpop, xlab="pharmacy", ylab ="lpop")
abline(pharmodel2)
summary(pharmodel2)
summ(pharmodel2)
par(mfrow=c(2,2))
plot(pharmodel2,1)
plot(pharmodel2,2)
plot(pharmodel2,3)
plot(pharmodel2,4)

lpdatapha2 <- lpdatapha[-4,]
pharmodel3 <- lm(lpop~pharmacy, data = lpdatapha2)
plot(lpdatapha2$pharmacy, lpdatapha2$lpop, xlab="pharmacy", ylab ="lpop")
abline(pharmodel3)
summary(pharmodel3)
summ(pharmodel3)
par(mfrow=c(2,2))
plot(pharmodel3,1)
plot(pharmodel3,2)
plot(pharmodel3,3)
plot(pharmodel3,4)

lpdatapha3 <- lpdatapha2[-15,]
pharmodel4 <- lm(lpop~pharmacy, data = lpdatapha3)
plot(lpdatapha3$pharmacy, lpdatapha3$lpop, xlab="pharmacy", ylab ="lpop")
abline(pharmodel4)
summary(pharmodel4)
summ(pharmodel4)
par(mfrow=c(2,2))
plot(pharmodel4,1)
plot(pharmodel4,2)
plot(pharmodel4,3)
plot(pharmodel4,4)

rm(list=ls())